# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock
  username: <%= ENV['DEVELOPMENT_DATABASE_USERNAME'] %>
  password: <%= ENV['DEVELOPMENT_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE_NAME'] %>
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
