# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02e4c32bed8c8bc6eb4e0539e5e06e8114a518aa3bfc95de27a7c9cc69aacc53e9f53c8d25b25a5579ff501535d82cf5b7951566f2b1a704412fa28e8b2a26b2

test:
  secret_key_base: 53be4531cf23dee23874bc5e5b85170e3e1970fe9eb444c1049e3add46a5cf10c2c132abc6fbe926e041562fabe484d148f8f04966b64936a2ec547e7c189231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
